import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/loginseven">LoginSeven</Link>
        </li>
        <li>
          <Link to="/login7register">Login7Register</Link>
        </li>
        <li>
          <Link to="/cartpage">CARTPAGE</Link>
        </li>
        <li>
          <Link to="/productpagedescription">PRODUCTPAGEDESCRIPTION</Link>
        </li>
        <li>
          <Link to="/productpagereviews">PRODUCTPAGEREVIEWS</Link>
        </li>
        <li>
          <Link to="/account">ACCOUNT</Link>
        </li>
        <li>
          <Link to="/orders">ORDERS</Link>
        </li>
        <li>
          <Link to="/addresses">ADDRESSES</Link>
        </li>
        <li>
          <Link to="/wishlist">WISHLIST</Link>
        </li>
        <li>
          <Link to="/cover">COVER</Link>
        </li>
        <li>
          <Link to="/homepage">HOMEPAGE</Link>
        </li>
        <li>
          <Link to="/frame48095563">Frame48095563</Link>
        </li>
        <li>
          <Link to="/homepageone">HOMEPAGEOne</Link>
        </li>
        <li>
          <Link to="/frame48095564">Frame48095564</Link>
        </li>
        <li>
          <Link to="/financeversionone">FinanceVersionOne</Link>
        </li>
        <li>
          <Link to="/cartmodal">CARTMODAL</Link>
        </li>
        <li>
          <Link to="/card">Card</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
